# Generated by Django 3.2.2 on 2021-11-28 12:49

import apps.files.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.file_path)),
                ('file_name', models.TextField()),
            ],
        ),
    ]
